baseURL = "http://example.org/"
languageCode = "en-us"
title = "Pop20"
theme = "hugo-ink"
paginate = 10

copyright = "Popagandhi since 2000."

# Static Dir

staticDir = ["static"]

[params]
	subtitle = "Reinventing my personal blog"
    avatar = "http://placecorgi.com/250/250"

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/skinnylatte"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"